---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name: 
        - htop
        - emacs
        - vim
        - alacritty
        - code
        - dolphin
        - gparted
        - qbittorrent
        - thunderbird
