- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - xclip
        - lxsession
        - volumeicon
        - rofi-emoji
        - rofi-calc
        - libqalculate
        - pacman-contrib
        - vim
        - alacritty
        - fastfetch
        - clipmenu
        - starship
        - ranger
        - exa
        - gparted
        - okular
        - vlc
        - dolphin
        - dunst
        - libreoffice-fresh
        - qbittorrent
        - feh
        - tmux
        - cronie
        - openssh
        - xterm
        - dmenu
        - rofi
        - i3
        - i3blocks
        - i3lock
        - network-manager-applet
        - acpi
        - python3
        - qtile
        - python-dbus-next
        - tigervnc
        - neovim
        - nodejs
        - npm
        - ttf-font-awesome
        - otf-font-awesome
        - ttf-sourcecodepro-nerd
        - ttf-ubuntu-font-family
        - ttf-mononoki-nerd
        - ttf-jetbrains-mono-nerd
        - lxappearance
        - xdotool
        - steam
        - wine
        - winetricks
        - lutris

  - name: Make .local/bin
    ansible.builtin.file:
      path: /home/fred/.local/bin
      state: directory
      
  - name: Make .local/share/applications folder
    ansible.builtin.file:
      path: /home/fred/.local/share/applications
      state: directory 

  - name: Start SSHD
    service:
      name: sshd
      state: started
      enabled: yes

  - name: Start cronie.service
    service:
      name: cronie
      state: started
      enabled: yes

  - name: Start bluetooth.service
    service:
      name: bluetooth.service
      state: started
      enabled: yes

  - name: Link alacritty
    ansible.builtin.file:
      src: /home/fred/github/ansible/files/alacritty
      dest: /home/fred/.config/alacritty
      state: link

  - name: Link Bashrc
    ansible.builtin.file:
      src: /home/fred/github/ansible/files/bashrc
      dest: /home/fred/.bashrc
      state: link

  - name: Link i3
    ansible.builtin.file:
      src: /home/fred/github/ansible/files/i3
      dest: /home/fred/.config/i3
      state: link

  - name: Copy mimeapps.list
    copy:
      src: /home/fred/github/ansible/files/.local/share/applications/mimeapps.list
      dest: /home/fred/.local/share/applications/mimeapps.list
      owner: fred
      group: fred

  - name: Link picom
    ansible.builtin.file:
      src: /home/fred/github/ansible/files/picom
      dest: /home/fred/.config/picom
      state: link

  - name: Link qtile
    ansible.builtin.file:
      src: /home/fred/github/ansible/files/qtile
      dest: /home/fred/.config/qtile
      state: link

  - name: Link rofi
    ansible.builtin.file:
      src: /home/fred/github/ansible/files/rofi
      dest: /home/fred/.config/rofi
      state: link

  - name: Link tmux.conf
    ansible.builtin.file:
      src: /home/fred/github/ansible/files/tmux.conf
      dest: /home/fred/.tmux.conf
      state: link

  - name: Link vnc
    ansible.builtin.file:
      src: /home/fred/github/ansible/files/vnc
      dest: /home/fred/.vnc
      state: link

  - name: Link wallpapers
    ansible.builtin.file:
      src: /home/fred/github/ansible/files/wallpapers
      dest: /home/fred/Pictures/wallpapers
      state: link

  - name: Link wifimenu
    ansible.builtin.file:
      src: /home/fred/github/ansible/files/.local/bin/wifimenu
      dest: /home/fred/.local/bin/wifimenu
      state: link

  - name: Add ansible user
    user:
      name: velociraptor
      system: yes

  - name: Set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: Ansible auto-provision
      user: velociraptor
      minute: "*/1"
      job: ansible-pull -o -U https://github.com/rider48371/ansible_laptop.git
