---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - emacs
        - vim
        - alacritty
        - code
        - dolphin
        - gparted
        - qbittorrent
        - thunderbird
        - nitrogen
        - cronie

  - name: Start SSHD
    service:
      name: sshd
      state: started
      enabled: yes

  - name: Start cronie.service
    service:
      name: cronie
      state: started
      enabled: yes

  - name: Copy bashrc
    copy:
      src: files/bashrc
      dest: /home/fred/.bashrc
      owner: fred
      group: fred

  - name: Copy Alacritty
    copy:
      src: files/alacritty
      dest: /home/fred/.config/alacritty
      owner: fred
      group: fred

  - name: Copy Conky
    copy:
      src: files/conky
      dest: /home/fred/.config
      owner: fred
      group: fred

  - name: Copy Dunst
    copy:
      src: files/dunst
      dest: /home/fred/.config
      owner: fred
      group: fred

  - name: Copy i3
    copy:
      src: files/i3
      dest: /home/fred/.config
      owner: fred
      group: fred

  - name: Copy neofetch
    copy:
      src: files/neofetch
      dest: /home/fred/.config
      owner: fred
      group: fred

  - name: Copy nitrogen
    copy:
      src: files/nitrogen
      dest: /home/fred/.config
      owner: fred
      group: fred

  - name: Copy rofi
    copy:
      src: files/rofi
      dest: /home/fred/.config
      owner: fred
      group: fred

  - name: Copy Onedrive
    copy:
      src: files/onedrive
      dest: ~/Documents
      owner: fred
      group: fred

  - name: Copy xmobar
    copy:
      src: files/xmobar
      dest: /home/fred/.config
      owner: fred
      group: fred

  - name: Copy xmonad
    copy:
      src: files/xmonad
      dest: /home/fred/.config
      owner: fred
      group: fred

  - name: Add ansible user
    user:
      name: velociraptor
      system: yes

  - name: Set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: Ansible auto-provision
      user: velociraptor
      minute: "*/1"
      job: ansible-pull -o -U https://github.com/rider48371/ansible.git
